#------------------------------------------------------------------------------#

schools_list = {
    'CEFET-MG': ['no', 'Centro Federal de Educação Tecnológica de Minas Gerais',                  ],
    'CPII'    : ['no', 'Colégio Pedro II',                                                        ],
    'FUFS'    : ['na', 'Universidade Federal de Sergipe',                                         ],
    'FURG'    : ['na', 'Universidade Federal do Rio Grande',                                      ],
    'IFPI'    : ['no', 'Instituto Federal do Piauí',                                              ],
    'IFRS'    : ['no', 'Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Sul',],
    'IFSP'    : ['no', 'Instituto Federal de São Paulo',                                          ],
    'IMPA'    : ['no', 'Instituto Nacional de Matemática Pura e Aplicada',                        ],
    'PUC-RJ'  : ['na', 'Pontifícia Universidade Católica do Rio de Janeiro',                      ],
    'UDESC'   : ['na', 'Universidade do Estado de Santa Catarina',                                ],
    'UEA'     : ['na', 'Universidade do Estado do Amazonas',                                      ],
    'UECE'    : ['na', 'Universidade Estadual do Ceará',                                          ],
    'UEFS'    : ['na', 'Universidade Estadual de Feira de Santana',                               ],
    'UEL'     : ['na', 'Universidade Estadual de Londrina',                                       ],
    'UEM'     : ['na', 'Universidade Estadual de Maringá',                                        ],
    'UEMA'    : ['na', 'Universidade Estadual do Maranhão',                                       ],
    'UEMS'    : ['na', 'Universidade Estadual de Mato Grosso do Sul',                             ],
    'UENF'    : ['na', 'Universidade Estadual do Norte Fluminense',                               ],
    'UEPB'    : ['na', 'Universidade Estadual da Paraíba',                                        ],
    'UEPG'    : ['na', 'Universidade Estadual de Ponta Grossa',                                   ],
    'UERJ'    : ['na', 'Universidade do Estado do Rio de Janeiro',                                ],
    'UESB'    : ['na', 'Universidade Estadual do Sudoeste da Bahia',                              ],
    'UESC'    : ['na', 'Universidade Estadual de Santa Cruz',                                     ],
    'UESPI'   : ['na', 'Universidade Estadual do Piauí',                                          ],
    'UFABC'   : ['na', 'Universidade Federal do ABC',                                             ],
    'UFAC'    : ['na', 'Universidade Federal do Acre',                                            ],
    'UFAL'    : ['na', 'Universidade Federal de Alagoas',                                         ],
    'UFAM'    : ['na', 'Universidade Federal do Amazonas',                                        ],
    'UFBA'    : ['na', 'Universidade Federal da Bahia',                                           ],
    'UFC'     : ['na', 'Universidade Federal do Ceará',                                           ],
    'UFCA'    : ['na', 'Universidade Federal do Cariri',                                          ],
    'UFCAT'   : ['na', 'Universidade Federal de Catalão',                                         ],
    'UFCG'    : ['na', 'Universidade Federal de Campina Grande',                                  ],
    'UFERSA'  : ['na', 'Universidade Federal Rural do Semi-Árido',                                ],
    'UFES'    : ['na', 'Universidade Federal do Espírito Santo',                                  ],
    'UFF'     : ['na', 'Universidade Federal Fluminense',                                         ],
    'UFFS'    : ['na', 'Universidade Federal da Fronteira Sul',                                   ],
    'UFG'     : ['na', 'Universidade Federal de Goiás',                                           ],
    'UFGD'    : ['na', 'Universidade Federal da Grande Dourados',                                 ],
    'UFJ'     : ['na', 'Universidade Federal de Jataí',                                           ],
    'UFJF'    : ['na', 'Universidade Federal de Juiz de Fora',                                    ],
    'UFLA'    : ['na', 'Universidade Federal de Lavras',                                          ],
    'UFMA'    : ['na', 'Universidade Federal do Maranhão',                                        ],
    'UFMS'    : ['na', 'Universidade Federal de Mato Grosso do Sul',                              ],
    'UFMT'    : ['na', 'Universidade Federal de Mato Grosso',                                     ],
    'UFOB'    : ['na', 'Universidade Federal do Oeste da Bahia',                                  ],
    'UFOP'    : ['na', 'Universidade Federal de Ouro Preto',                                      ],
    'UFOPA'   : ['na', 'Universidade Federal do Oeste do Pará',                                   ],
    'UFPA'    : ['na', 'Universidade Federal do Pará',                                            ],
    'UFPB'    : ['na', 'Universidade Federal da Paraíba',                                         ],
    'UFPI'    : ['na', 'Universidade Federal do Piauí',                                           ],
    'UFPR'    : ['na', 'Universidade Federal do Paraná',                                          ],
    'UFR'     : ['na', 'Universidade Federal de Rondonópolis',                                    ],
    'UFRB'    : ['na', 'Universidade Federal do Recôncavo da Bahia',                              ],
    'UFRJ'    : ['na', 'Universidade Federal do Rio de Janeiro',                                  ],
    'UFRN'    : ['na', 'Universidade Federal do Rio Grande do Norte',                             ],
    'UFRPE'   : ['na', 'Universidade Federal Rural de Pernambuco',                                ],
    'UFRR'    : ['na', 'Universidade Federal de Roraima',                                         ],
    'UFRRJ'   : ['na', 'Universidade Federal Rural do Rio de Janeiro',                            ],
    'UFS'     : ['na', 'Universidade Federal de Sergipe',                                         ],
    'UFSC'    : ['na', 'Universidade Federal de Santa Catarina',                                  ],
    'UFSCAR'  : ['na', 'Universidade Federal de São Carlos',                                      ],
    'UFSJ'    : ['na', 'Universidade Federal de São João del-Rei',                                ],
    'UFSM'    : ['na', 'Universidade Federal de Santa Maria',                                     ],
    'UFT'     : ['na', 'Universidade Federal do Tocantins',                                       ],
    'UFTM'    : ['na', 'Universidade Federal do Triângulo Mineiro',                               ],
    'UFU'     : ['na', 'Universidade Federal de Uberlândia',                                      ],
    'UFV'     : ['na', 'Universidade Federal de Viçosa',                                          ],
    'UFVJM'   : ['na', 'Universidade Federal do Vale do Jequitinhonha e Mucuri',                  ],
    'UNEMAT'  : ['na', 'Universidade do Estado de Mato Grosso',                                   ],
    'UNESP'   : ['na', 'Universidade Estadual Paulista',                                          ],
    'UNICAMP' : ['na', 'Universidade Estadual de Campinas',                                       ],
    'UNIFAL'  : ['na', 'Universidade Federal de Alfenas',                                         ],
    'UNIFAP'  : ['na', 'Universidade Federal do Amapá',                                           ],
    'UNIFESP' : ['na', 'Universidade Federal de São Paulo',                                       ],
    'UNILAB'  : ['na', 'Universidade da Integração Internacional da Lusofonia Afro-Brasileira',   ],
    'UNIOESTE': ['na', 'Universidade Estadual do Oeste do Paraná',                                ],
    'UNIPAMPA': ['na', 'Universidade Federal do Pampa',                                           ],
    'UNIR'    : ['na', 'Universidade Federal de Rondônia',                                        ],
    'UNIRIO'  : ['na', 'Universidade Federal do Estado do Rio de Janeiro',                        ],
    'UNIVASF' : ['na', 'Universidade Federal do Vale do São Francisco',                           ],
    'URCA'    : ['na', 'Universidade Regional do Cariri',                                         ],
    'USP'     : ['na', 'Universidade de São Paulo',                                               ],
    'UTFPR'   : ['na', 'Universidade Tecnológica Federal do Paraná',                              ],
    'UnB'     : ['na', 'Universidade de Brasília',                                                ],
  }


#------------------------------------------------------------------------------#